### ISSUE TITLE
Handle Network Share Failures Correctly

### ISSUE THREAD

**Issue by ytausch** [ytausch/SchoolDisplay#19]
It looks like the application crashes when `PdfDirectoryPath` becomes unavailable.

I will try to reproduce this.

**Comment by ytausch** [comment]
# Steps to reproduce

1. Set `PdfDirectoryPath` to a **working** network share folder
2. Start the application
3. **Disconnect** the network share server
4. Wait around 60 seconds (the clock stops ticking!)
5. Get this exception:

```
System.IO.IOException: The network path was not found.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern)
   at SchoolDisplay.Data.Pdf.PdfRepository.ListAllFiles()
   at SchoolDisplay.Data.Pdf.CyclicPdfService.GetNextFileName(Boolean includeCurrentFile)
   at SchoolDisplay.Data.Pdf.CyclicPdfService.GetNextDocument()
   at SchoolDisplay.MainForm.LoadNextPdf()
   at SchoolDisplay.Display.Scroller.<ScrollOneUnit>d__12.MoveNext()
--- End of stack monitoring from previous location where exception was thrown ---.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```
<sup>(note: I translated this to English)</sup>

It looks like the error occurs here: https://github.com/ytausch/SchoolDisplay/blob/67c1658e464b675a1300d3ba4c23e2b30f3d0009/SchoolDisplay/SchoolDisplay/Data/Pdf/PdfRepository.cs#L34-L42

# How to stop crashing
These changes would prevent the crash:

```c#
/// <summary>
/// Get a IEnumerable of all available PDF files.
/// </summary>
/// <returns>A string list of PDF file names.</returns>
public IEnumerable<string> ListAllFiles()
{
    // hide implementation details by only returning the filename, not the path.
    try
    {
        return Directory.EnumerateFiles(directoryPath, "*.pdf").Select(file => Path.GetFileName(file));
    }
    catch
    {
        // since a lot of unexcepted Exceptions can happen when doing file operations,
        // we exceptionally catch all of them here for maximum reliability.
        return Enumerable.Empty<string>();
    }
}
```

Of course, this does not let us differentiate between an empty folder and an unreachable network share - but we already hide error messages by design.

# FileSystemWatcher disconnected
There is another issue when handling network share failues: `FileSystemWatcher` will stop raising events if there was a network drive failure - **even if** the connection is restored afterwards. We should be able to resolve this by **resetting [`EnableRaisingEvents`](https://docs.microsoft.com/de-de/dotnet/api/system.io.filesystemwatcher.enableraisingevents?view=net-5.0)** **regularily** (e. g. every 60 seconds) or after we recover from a network drive failure:

```c#
fsWatcher.EnableRaisingEvents = false;
fsWatcher.EnableRaisingEvents = true;
```
Note that doing so can raise exceptions - e.g. if the network drive is still not available. We need to handle those correctly.

# Network drive failure at initial start
If the network drive fails before the intial start of the application, we already handle everything correctly (and show an appropriate error message). Nothing needs to be done here.

# Further optimizations
If possible, file operations should generally not happen on the main thread - maybe we should do this in the future. This would stop the clock hanging if there is something going wrong loading the next file.
